### PR TITLE
[MyPerf4J-87] Fix windows env getConfigFileDir is empty #87

### LINKED ISSUE #87: window环境下配置文件路径获取错误
**Bug 描述** 

image

### PR DESCRIPTION
**Pull request by JiaRG**
## What is the purpose of the change

fix #87

## Brief ChangeLog

Fix windows env getConfigFileDir is empty

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/LinShunKang/MyPerf4J/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[MyPerf4J-XXX] Fix NullPointerException when host is null #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist.
- [x] Run `mvn clean package -Dmaven.test.skip=false` to make sure unit-test pass.

### CODE REVIEW

File: MyPerf4J-Core/src/test/java/cn/myperf4j/core/SystemPropertiesTest.java [hunk 1]
```diff
@@ -1,14 +1,34 @@
...
+
 /**
  * Created by LinShunkang on 2019/07/28
  */
 public class SystemPropertiesTest {
 
     @Test
     public void test() {
+        // windows下os.name的返回值是以 Windows 开头的
+        Assert.assertFalse(System.getProperty("os.name").startsWith("windows"));
```
Comment (LinShunKang) [inline MyPerf4J-Core/src/test/java/cn/myperf4j/core/SystemPropertiesTest.java:16]: 可以把这段代码抽取成一个单独的方法：testParseConfigFilePath

File: MyPerf4J-Core/src/main/java/cn/myperf4j/core/AbstractBootstrap.java [hunk 2]
```diff
@@ -181,12 +181,7 @@ private boolean initProperties() {
     }
 
     private String getConfigFileDir(String configFilePath) {
```
Comment (LinShunKang) [inline MyPerf4J-Core/src/main/java/cn/myperf4j/core/AbstractBootstrap.java:183]: 可以重命名为 parseConfigFileDir

**Comment by LinShunKang** [comment]
Thanks : )
